### PR TITLE
fix(button-toggle): disabled style fix

### LINKED ISSUE #2087: Toggle button doesn't show button enabled until I click on it
**Summary**

**Reproduction**

Steps to reproduce:

1. Add a disabled tag to one of the buttons in the button toggle component
2. Add a button to set a isDisabled property to true/false
3. Disable the toggle button by clicking in the button added in step 2
4. Now enable the button again
Expected: Button shows as enabled
Actual: Button still looks disabled. If you click on the button it will then show as enabled

Stackblitz reproduction (click the "Edit on Stackblitz" link on a component example and fork the template):
https://stackblitz.com/edit/angular-qnappg?file=src/app/button-toggle-styles/button-toggle-styles-example.component.html

### PR DESCRIPTION
**Pull request by andrew-frueh**
fix removing disabled style after turning off disabled

closes #2087

### CODE REVIEW

**Review by viroivo82 — APPROVED** [review]
Good job!

File: projects/cashmere/src/lib/button-toggle/button-toggle.component.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ export class ButtonToggleComponent {
             this._hostClass += ' hc-toggle-disabled';
         }
         if ( !this._disabled && this._hostClass.includes( 'hc-toggle-disabled' )) {
-            this._hostClass.replace( ' hc-toggle-disabled', '' );
+            this._hostClass = this._hostClass.replace( ' hc-toggle-disabled', '' );
```
Comment (aaronbrethorst) [inline projects/cashmere/src/lib/button-toggle/button-toggle.component.ts:50]: is the leading space on `' hc-toggle-disabled'` a typo or intentional?

Comment (andrew-frueh) [reply projects/cashmere/src/lib/button-toggle/button-toggle.component.ts:50]: Yeah that one is actually intentional because `hostClass` is a list of classes on the element - without that leading space, it'll leave a whitespace character at the end of the class list which Angular doesn't like

**Review by aaronbrethorst — APPROVED** [review]
lgtm 🚢
