### PR TITLE
fix(datepicker): fixed the minutes max/min

### LINKED ISSUE #1628: DATEPICKER - Cannot set MINUTES time to exactly '00' using the up/down arrows
**Summary**

On the DatePicker control, cannot set the MINUTES time to exactly '00' using the up/down arrows.  For example '3:00 PM'

**Reproduction**

image

### PR DESCRIPTION
**Pull request by WistyDagel**
closes #1628

### CODE REVIEW

**Review by corykon — APPROVED** [review]

File: projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts [hunk 1]
```diff
@@ -567,7 +567,7 @@ export class CalendarComponent implements AfterContentInit, AfterViewChecked, On
             let curMin = +this.minutes;
             curMin++;
             if (curMin > 59) {
-                curMin = 59;
+                curMin = 1;
```
Comment (andrew-frueh) [inline projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts:570]: hey @WistyDagel - this should actually get set to 0 instead of 1 so that 3:59 loops to 3:00 instead of 3:01

**Review by andrew-frueh — CHANGES_REQUESTED** [review]
One fix here and then good to go

**Review by andrew-frueh — APPROVED** [review]
