### PR TITLE
add core-js/es6/object poly fill to fix IE11 popover bug

### LINKED ISSUE #199: popover doesn't trigger in IE 11
Reproduced in IE 11.125.16299.0 on windows 10

### PR DESCRIPTION
**Pull request by benjanderson**
IE 11 doesn't have object.assign, a quick google led to this very simple solution. Tested the popover now triggers properly 😄 

Closes #199

### CODE REVIEW

File: docs/polyfills.ts [hunk 1]
```diff
@@ -1,70 +1,70 @@
...
-/**
- * Date, currency, decimal and percent pipes.
- * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
- */
-// import 'intl';  // Run `npm install --save intl`.
-/**
- * Need to import at least one locale-data with intl.
- */
-// import 'intl/locale-data/jsonp/en';
+/**
```
Comment (benjanderson) [inline docs/polyfills.ts]: stupid line ending changes
