### PR TITLE
fix(datepicker): validation with null init value

### LINKED ISSUE #982: Date type validation not firing when text entered into DatePicker input.
**Summary**

We have several reactive forms in our Care Management Angular application that contain DatePicker input fields (using the Cashmere DatePicker component).  For fields that are not required and have no default date set, the user can enter text and either tab or submit with no date-type validation firing.

If you do set a default date on initial render and then enter text, the date-type validation will work as expected.

Link to demonstration video created by Joe Skeen: 
https://slack-files.com/T04807US5-FLE31V17H-99129ea2fc

**Reproduction**

Stackblitz forked example:
https://angular-tmcxwy.stackblitz.io

**Additional context**

Link to conversation in Cashmere Slack channel (originally posted by Chad Rockwell on 07/11/2019):
https://healthcatalyst.slack.com/archives/C75LHAV9S/p1562880691016500

### PR DESCRIPTION
**Pull request by andrew-frueh**
fix that prevented validation when the initial bound value wasn't set

closes #982

### CODE REVIEW

File: projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.ts [hunk 1]
```diff
@@ -1,15 +1,10 @@
...
 })
-export class DatepickerExampleComponent implements OnInit {
-    constructor() {}
-
+export class DatepickerExampleComponent {
     date1 = new Date(2010, 1, 1);
-    date2 = new Date(2010, 1, 1);
-
-    ngOnInit() {}
 }
```
Comment (andrew-frueh) [inline projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.ts]: Simplifying up the example ts - there was old code in here that wasn't being used.

File: projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.scss [hunk 2]
```diff
@@ -3,6 +3,6 @@
     height: 70px;
 }
 
-.form-container {
+.hc-calendar-wrapper > .form-container {
     padding-left: 13px;
```
Comment (andrew-frueh) [inline projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.scss]: `.form-container` was actually colliding with a couple other examples on the demo site.  So I moved it into specific namespace for the component to make sure this wouldn't happen in any apps.

File: projects/cashmere/src/lib/datepicker/calendar-body/calendar-body.component.html [hunk 3]
```diff
@@ -11,8 +11,6 @@
         aria-hidden="true"
         class="hc-calendar-body-label"
         [attr.colspan]="_firstRowOffset"
-        [style.paddingTop]="_cellPadding"
-        [style.paddingBottom]="_cellPadding"
```
Comment (andrew-frueh) [inline projects/cashmere/src/lib/datepicker/calendar-body/calendar-body.component.html]: I saw this happening in Patient Safety Monitor so just adding the fix to this PR.  This padding on the top and bottom of the spacer was making an abnormally large first row.
Screen Shot 2019-10-10 at 12 46 46 PM
