### PR TITLE
fix(date-range): options set after nginit not taking effect

### LINKED ISSUE #729: Date range options cant change after "ngOnInit"
**Describe the bug**
Options set after "ngOnit" aren't taking effect. Since this is a fairly new component I wanted to get this out before anyone adopts this and finds the bug

### PR DESCRIPTION
**Pull request by benjanderson**
BREAKING CHANGE: moved date binding from options to selectedDate

fix #729

### CODE REVIEW

File: projects/cashmere-examples/src/lib/date-range/date-range-example.component.ts [hunk 1]
```diff
@@ -23,9 +23,7 @@ export class DateRangeExampleComponent implements OnInit {
         this.options = {
             presets: this.presets,
             format: 'mediumDate',
-            range: {fromDate: today, toDate: today},
             applyLabel: 'Apply',
-            // excludeWeekends:true,
```
Comment (joeskeen) [inline projects/cashmere-examples/src/lib/date-range/date-range-example.component.ts]: should this be removed?
