### PR TITLE
fix(tabs): defaultTab accepts number

### LINKED ISSUE #1021: TabSetComponent.defaultTab should accept a number
**Summary**

The description for TabSetComponent.defaultTab says "Zero-based numerical value..." but the type is `string`, likely because it accepts `none` as a value. This is confusing; the type should probably be `string | number` to allow either kind of input, so we don't have to cast numbers to string for a numerical value.

### PR DESCRIPTION
**Pull request by andrew-frueh**
allow the defaultTab parameter to accept either a string or a number

closes #1021

### CODE REVIEW

File: projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts [hunk 1]
```diff
@@ -68,11 +68,11 @@ export class TabSetComponent implements AfterContentInit {
...
      * will be immediately selected. Defaults to 0 (the first tab). */
     @Input()
-    get defaultTab(): string {
+    get defaultTab(): string | number {
         return this._defaultTab;
     }
 
-    set defaultTab(tabValue: string) {
+    set defaultTab(tabValue: string | number) {
         if (Number(tabValue) !== NaN || tabValue === 'none') {
```
Comment (joeskeen) [inline projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts]: This is actually not correct, since `NaN !== NaN`.  Should use `isNaN()` instead

File: projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts [hunk 2]
```diff
@@ -38,7 +38,7 @@ export function invalidDefaultTab(tabVal: string) {
 export class TabSetComponent implements AfterContentInit {
     _routerEnabled: boolean = false;
     private _direction: string = 'vertical';
-    private _defaultTab: string = '0';
+    private _defaultTab: string | number = '0';
```
Comment (joeskeen) [inline projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts]: Since we're accepting a number, shouldn't the default just be `0`? That way we can save < 1ms of parsing that every single time.

File: projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts (hunk 1 above)
Comment (joeskeen) [reply projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts]:
```ts
if (!isNaN(+tabValue) || tabValue === 'none') {
```

Comment (andrew-frueh) [reply projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts]: Oh I just saw the second post - is there a difference between `isNaN(+tabValue)` and `isNaN(Number(tabValue))`
