### PR TITLE
fix(am-pm automatic switching): am and pm times switch automatically

### LINKED ISSUE #1338: AM/PM does not automatically switch when changing time
Not so much a bug as some behavior that some users are finding to be unexpected:

> Wanted to report a bug in scheduling within Ops Console. When you click the down arrow on the time it should automatically change from PM to AM, it does not do this though. In my example if I have it set to 12:30 PM and want it to run an hour earlier, I should be able to just click the down arrow on the hour and it would resolve to 11:30 AM. Current functionality is that it would resolve to 11:30 PM (11 hours later)... [Version DOS 20.2]

image

### PR DESCRIPTION
**Pull request by Victor1818**
closes #1338

### CODE REVIEW

File: projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts [hunk 1]
```diff
@@ -532,7 +532,14 @@ export class CalendarComponent implements AfterContentInit, AfterViewChecked, On
             curHour++;
             const tempCycle = this._hourCycle > 12 ? 23 : 12;
             if (curHour > tempCycle) {
-                curHour = tempCycle;
+                curHour = this._hourCycle > 12 ? 0 : 1;
+            }
+            if (curHour === 12) {
+                if (this._period.value === 'am') {
```
Comment (jonest) [inline projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts:538]: Pretty minor, but looks like this whole conditional for `am`, `pm` switch is something that could probably be pulled into a single method

Comment (jonest) [reply projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts:538]: Or instead to make it more simple, just a ternary (assuming that it's always going to be `am` or `pm`? I'm not sure if there's a 24-hour setup for this

File: projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts [hunk 2]
```diff
@@ -532,7 +532,14 @@ export class CalendarComponent implements AfterContentInit, AfterViewChecked, On
             curHour++;
             const tempCycle = this._hourCycle > 12 ? 23 : 12;
             if (curHour > tempCycle) {
-                curHour = tempCycle;
+                curHour = this._hourCycle > 12 ? 0 : 1;
```
Comment (jonest) [inline projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts:535]: I don't really understand what's being accomplished here (I don't really know the code for the date picker stuff)

File: projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts (hunk 1 above)
Comment (Victor1818) [reply projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts:538]: @jonest A separate method is what I was also thinking too. I can try a few things with the ternary but if that doesn't work, would you have an alternative idea?

File: projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts (hunk 2 above)
Comment (Victor1818) [reply projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts:535]: @jonest This line allows the 12 hour or 24 hour clock to cycle instead of having a max of 12 and 24 hours respectively and a min of 1 and 0 hours respectively.

File: projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts [hunk 3]
```diff
@@ -546,12 +547,19 @@ export class CalendarComponent implements AfterContentInit, AfterViewChecked, On
...
             if (curHour < tempCycle) {
-                curHour = tempCycle;
+                curHour = this._hourCycle > 12 ? 23 : 12;
             }
+            this._changeMeridiem(curHour, 11);
             this.hours = curHour.toString();
         }
     }
 
+    _changeMeridiem(curHour, hourChange) {
```
Comment (jonest) [inline projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts:557]: TIL it's spelled `meridiem` for time 😃

**Comment by jonest** [comment]
Whoops! I didn't think I had to do anything more to add my comments so sorry for the delay :/

File: projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts (hunk 2 above)
Comment (Victor1818) [reply projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts:535]: It just allows the time to reset at its lowest or highest hours instead of remaining at its lowest or highest hours

**Comment by andrew-frueh** [comment]
Thanks for the code review and working with @Victor1818 to wrap this one up @jonest.  Really appreciate it.
